fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        app:
            client: default
            settings:
                index:
                    analysis:
                        analyzer:
                            search_analyzer:
                                type: custom
                                tokenizer: standard
                                filter: [standard, lowercase, asciifolding, french_stemmer, french_stop]
                            index_analyzer:
                                type: custom
                                tokenizer: standard
                                filter: [standard, lowercase, asciifolding, french_stemmer, french_stop, custom_filter]
                            facet_analyzer:
                                type: custom
                                tokenizer: keyword
                                filter: [standard, lowercase, asciifolding, trim]
                            facetMulti_analyzer:
                                type: custom
                                tokenizer: my_tokenizer
                                filter: [standard, lowercase, asciifolding, trim]
                                  
                        tokenizer:
                            my_tokenizer: 
                                type: simple_pattern_split
                                pattern: "|"
                        query:
                            query_string: 
                                #query: "kimchy\\"
                                fields  : ["resource.*"]
                                allow_leading_wildcard: true
                                default_operator: AND
                                #fuzzy_max_expansions: 2
                                #phrase_slop: 2
                                #refix_length: 3
                                #zero_terms_query: all
                                #term:
                                    #auteur: keyword
                                match:
                                    auteur:
                                        operator: and
                                        zero_terms_query: all

                        stored_fields: ['_none_']
                        #match_phrase_prefix: 
                            #auteur:
                                #zero_terms_query: all
                        mappings:
                            properties:
                                 auteur: keyword

                        filter:
                            french_elision:
                                type: elision
                                articles_case: true
                                articles: ['l', 'm', 't', 'qu', 'n', 's','j', 'd', 'c', 'jusqu', 'quoiqu','lorsqu', 'puisqu']
                            french_stop:
                                type: stop
                                stopwords: _french_
                            french_keywords:
                                type: keyword_marker
                                keywords: []
                            french_stemmer:
                                type: stemmer
                                language: french
                            custom_filter:
                                type: edgeNGram
                                side: front
                                min_gram: 1
                                max_gram: 20
            types:
                resource:
                    dynamic: false
                    properties:
                        id: ~
                        title:
                            analyzer: facetMulti_analyzer
                            search_analyzer: search_analyzer
                            type: text
                            boost: 8
                        type:
                            analyzer: facet_analyzer
                            search_analyzer: search_analyzer
                            type: text
                            fielddata: true
                        person:
                            analyzer: facetMulti_analyzer
                            search_analyzer: search_analyzer
                            type: text
                            fielddata: true
                            boost: 5 
                        oeuvre:
                            analyzer: facetMulti_analyzer
                            search_analyzer: search_analyzer
                            type: text
                            fielddata: true
                            boost: 3
                        organisme:
                            analyzer: facetMulti_analyzer
                            search_analyzer: search_analyzer
                            type: text
                            fielddata: true
                            boost: 3
                        geo: &ent_text
                            analyzer: index_analyzer
                            search_analyzer: search_analyzer
                            type: text
                        tag: 
                            analyzer: facetMulti_analyzer
                            search_analyzer: search_analyzer
                            type: text
                            fielddata: true
                            boost: 3
                        auteur: 
                            analyzer: facetMulti_analyzer
                            search_analyzer: search_analyzer
                            type: text
                            fielddata: true
                            boost: 3
                            #index_options: offsets
                            #position_increment_gap : 2
                            
                            
                        anneedit: ~
                        collection: *ent_text
                        comment: *ent_text
                        
                    persistence:
                        driver: orm
                        model: App\Entity\Resource
                        repository: App\SearchRepository\SearchRepository
                        finder: ~
                        provider: ~
                        listener: ~

