fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        app:
            client: default
            settings:
                index:
                    analysis:
                        analyzer:
                            search_analyzer:
                                type: custom
                                tokenizer: standard
                                filter: [standard, lowercase, asciifolding, trim]
                            index_analyzer:
                                type: custom
                                tokenizer: standard
                                filter: [standard, lowercase, asciifolding, trim]
                                   
            types:
                resource:
                    dynamic: false
                    properties:
                        id: ~
                        title: &ent_text
                            analyzer: index_analyzer
                            search_analyzer: search_analyzer
                            type: text
                        person: *ent_text
                        oeuvre: *ent_text
                        organisme: *ent_text
                        geo: *ent_text
                        tag: *ent_text
                        auteur: *ent_text
                        anneedit: ~
                        collection: *ent_text
                        type:
                            fielddata: true
                    persistence:
                        driver: orm
                        model: App\Entity\Resource
                        repository: App\SearchRepository\SearchRepository
                        finder: ~
                        provider: ~

