vich_uploader:
    db_driver: orm

    mappings:
      resource_image:
         uri_prefix: /images/resources
         upload_destination: '%kernel.project_dir%/public/images/resources'
         namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'

    
    